/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket.com.pojo;

/**
 *
 * @author Robin Khan
 */


import java.util.HashSet;
import java.util.Set;

/**
 * BusInfo generated by hbm2java
 */
public class BusInfo  implements java.io.Serializable {

     private Integer busId;
     private int companyInfo;
     private int route;
     private int busNumber;
     private String busName;
     private String status;

    public BusInfo() {
    }

    public Integer getBusId() {
        return busId;
    }

    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    public int getCompanyInfo() {
        return companyInfo;
    }

    public void setCompanyInfo(int companyInfo) {
        this.companyInfo = companyInfo;
    }

    public int getRoute() {
        return route;
    }

    public void setRoute(int route) {
        this.route = route;
    }

    public int getBusNumber() {
        return busNumber;
    }

    public void setBusNumber(int busNumber) {
        this.busNumber = busNumber;
    }

    public String getBusName() {
        return busName;
    }

    public void setBusName(String busName) {
        this.busName = busName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    
   
}