/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket.com.pojo;

/**
 *
 * @author Robin Khan
 */
import java.util.HashSet;
import java.util.Set;

/**
 * Districtinfo generated by hbm2java
 */
public class Districtinfo  implements java.io.Serializable {

    private int disId;

    private String disName;
    private int divId;
    private Set upazilainfos = new HashSet(0);

    public int getDisId() {
        return disId;
    }

    public void setDisId(int disId) {
        this.disId = disId;
    }

 

    public String getDisName() {
        return disName;
    }

    public void setDisName(String disName) {
        this.disName = disName;
    }

    public int getDivId() {
        return divId;
    }

    public void setDivId(int divId) {
        this.divId = divId;
    }

    public Set getUpazilainfos() {
        return upazilainfos;
    }

    public void setUpazilainfos(Set upazilainfos) {
        this.upazilainfos = upazilainfos;
    }
     

    public Districtinfo() {
    }
      

    public Districtinfo(int disId, String disName, int divId) {
        this.disId = disId;
        
        this.disName = disName;
        this.divId = divId;
    }
     
    

  


}



