/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket.com.pojo;

/**
 *
 * @author Robin Khan
 */
import java.util.HashSet;
import java.util.Set;

/**
 * Divisioninfo generated by hbm2java
 */
public class Divisioninfo  implements java.io.Serializable {


     private int divId;
     private String divName;
     private Set districtinfos = new HashSet(0);

    public Divisioninfo() {
    }

    public Divisioninfo(String divName, Set districtinfos) {
       this.divName = divName;
       this.districtinfos = districtinfos;
    }
   
    public Integer getDivId() {
        return this.divId;
    }
    
    public void setDivId(Integer divId) {
        this.divId = divId;
    }
    public String getDivName() {
        return this.divName;
    }
    
    public void setDivName(String divName) {
        this.divName = divName;
    }
    public Set getDistrictinfos() {
        return this.districtinfos;
    }
    
    public void setDistrictinfos(Set districtinfos) {
        this.districtinfos = districtinfos;
    }




}
