package ticket.com.pojo;
// Generated May 31, 2015 12:08:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Upazilainfo generated by hbm2java
 */
public class Upazilainfo  implements java.io.Serializable {


     private int uzid;
     private Districtinfo districtinfo;
     private String uzname;
     private Set unioninfos = new HashSet(0);
     
     private int disId;

    public int getUzid() {
        return uzid;
    }

    public void setUzid(int uzid) {
        this.uzid = uzid;
    }

    public int getDisId() {
        return disId;
    }

    public void setDisId(int disId) {
        this.disId = disId;
    }
     
     

    public Upazilainfo() {
    }

    public Upazilainfo(Districtinfo districtinfo, String uzname, Set unioninfos) {
       this.districtinfo = districtinfo;
       this.uzname = uzname;
       this.unioninfos = unioninfos;
    }
   
 
    
    public void setUzid(Integer uzid) {
        this.uzid = uzid;
    }
    public Districtinfo getDistrictinfo() {
        return this.districtinfo;
    }
    
    public void setDistrictinfo(Districtinfo districtinfo) {
        this.districtinfo = districtinfo;
    }
    public String getUzname() {
        return this.uzname;
    }
    
    public void setUzname(String uzname) {
        this.uzname = uzname;
    }
    public Set getUnioninfos() {
        return this.unioninfos;
    }
    
    public void setUnioninfos(Set unioninfos) {
        this.unioninfos = unioninfos;
    }




}


