package ticket.com.pojo;


// Generated May 30, 2015 9:22:46 PM by Hibernate Tools 4.3.1



/**
 * UserAccessModule generated by hbm2java
 */
public class UserAccessModule  implements java.io.Serializable {


     private Integer accModId;
     private int userModule;
     private int userRole;

    public UserAccessModule() {
    }

  
   
    public Integer getAccModId() {
        return this.accModId;
    }
    
    public void setAccModId(Integer accModId) {
        this.accModId = accModId;
    }

    public int getUserModule() {
        return userModule;
    }

    public void setUserModule(int userModule) {
        this.userModule = userModule;
    }

    public int getUserRole() {
        return userRole;
    }

    public void setUserRole(int userRole) {
        this.userRole = userRole;
    }



}


