package ticket.com.pojo;
// Generated May 31, 2015 12:08:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wardinfo generated by hbm2java
 */
public class Wardinfo  implements java.io.Serializable {


     private int wdId;
     private Unioninfo unioninfo;
     private String wdName;
     private int upId;

    public int getWdId() {
        return wdId;
    }

    public void setWdId(int wdId) {
        this.wdId = wdId;
    }

    public int getUpId() {
        return upId;
    }

    public void setUpId(int upId) {
        this.upId = upId;
    }
     private Set villageinfos = new HashSet(0);

    public Wardinfo() {
    }

    public Wardinfo(Unioninfo unioninfo, String wdName, Set villageinfos) {
       this.unioninfo = unioninfo;
       this.wdName = wdName;
       this.villageinfos = villageinfos;
    }
   
   
    public Unioninfo getUnioninfo() {
        return this.unioninfo;
    }
    
    public void setUnioninfo(Unioninfo unioninfo) {
        this.unioninfo = unioninfo;
    }
    public String getWdName() {
        return this.wdName;
    }
    
    public void setWdName(String wdName) {
        this.wdName = wdName;
    }
    public Set getVillageinfos() {
        return this.villageinfos;
    }
    
    public void setVillageinfos(Set villageinfos) {
        this.villageinfos = villageinfos;
    }




}


